In [2]:
import numpy as np

print(np.__version__)

2.3.5


In [5]:
ar=np.array([1,2,3,4,5])
print(ar,type(ar),ar.shape)

ar1=np.array([1,2,3,4,5,'prime'])
print(ar1,type(ar1),ar1.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)


In [7]:
ar2=np.zeros((3,3))
print(ar2,type(ar2),ar2.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'> (3, 3)


In [8]:
ar3=np.ones((2,3))
print(ar3,type(ar3),ar3.shape)

[[1. 1. 1.]
 [1. 1. 1.]] <class 'numpy.ndarray'> (2, 3)


In [9]:
ar4=np.full((2,3),5)
print(ar4,type(ar4),ar4.shape)

[[5 5 5]
 [5 5 5]] <class 'numpy.ndarray'> (2, 3)


In [10]:
ar5=np.eye(3)
print(ar5,type(ar5),ar5.shape)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <class 'numpy.ndarray'> (3, 3)


In [12]:
ar6=np.arange(1,11)
ar7=np.arange(1,11,2)
print(ar6,type(ar6),ar6.shape)
print(ar7,type(ar7),ar7.shape)

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'> (10,)
[1 3 5 7 9] <class 'numpy.ndarray'> (5,)


In [5]:
ar8=np.linspace(1,100,4)
print(ar8,type(ar8),ar8.shape)

[  1.  34.  67. 100.] <class 'numpy.ndarray'> (4,)
