In [1]:
import numpy as np

print(np.__version__)

2.3.5


In [5]:
ar=np.array([1,2,3,4,5])
print(ar,type(ar),ar.shape)

ar1=np.array([1,2,3,4,5,'prime'])
print(ar1,type(ar1),ar1.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)


In [7]:
ar2=np.zeros((3,3))
print(ar2,type(ar2),ar2.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'> (3, 3)


In [8]:
ar3=np.ones((2,3))
print(ar3,type(ar3),ar3.shape)

[[1. 1. 1.]
 [1. 1. 1.]] <class 'numpy.ndarray'> (2, 3)


In [9]:
ar4=np.full((2,3),5)
print(ar4,type(ar4),ar4.shape)

[[5 5 5]
 [5 5 5]] <class 'numpy.ndarray'> (2, 3)


In [10]:
ar5=np.eye(3)
print(ar5,type(ar5),ar5.shape)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <class 'numpy.ndarray'> (3, 3)


In [12]:
ar6=np.arange(1,11)
ar7=np.arange(1,11,2)
print(ar6,type(ar6),ar6.shape)
print(ar7,type(ar7),ar7.shape)

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'> (10,)
[1 3 5 7 9] <class 'numpy.ndarray'> (5,)


In [5]:
ar8=np.linspace(1,100,4)
print(ar8,type(ar8),ar8.shape)

[  1.  34.  67. 100.] <class 'numpy.ndarray'> (4,)


In [6]:
ar9=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
print(ar9)

print(ar9.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64


In [15]:
#operations on array
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

print(arr.reshape(3,2))

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [17]:
flattened=arr.flatten()
print(flattened,flattened.shape)

[1 2 3 4 5 6] (6,)


In [22]:
#Indexing and slicing
print(arr[0])

#fencing
arr2d=np.array([1,2,3,4])
idx=[0,1,2]
print(arr2d[idx])

[1 2 3]
[1 2 3]


In [2]:
#boolean indexing
arr3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3d[arr3d>4])
print(arr3d[arr3d%2==0])

[5 6 7 8]
[2 4 6 8]


In [24]:
#slicing
#[start:stop:step]
print(arr3d[0:2,0:2,0:2])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
#Axes in multidimensional arrays
ar2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar2d)
print(np.sum(ar2d)) #sum of all elements
print(np.sum(ar2d, axis=0)) #sum along columns
print(np.sum(ar2d, axis=1)) #sum along rows



[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


In [4]:
#3D array
ar3d=np.array([ [ [1,2],[3,4],[5,6] ] ,[ [7,8],[9,10],[11,12] ] ])
print(ar3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [9]:
#Indexing
print(ar3d[0,1,1])
print(ar3d[1,1,0])

#Slicing
print(ar3d[:,0,:]) #first row from both array
print(ar3d[:,:,0]) #first column from both array

4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [ ]:
#Vectorization
arr=np.array([[1,2,3],[4,5,6]])
print(arr**2)
print(arr+10)
arr=arr*10
print(arr)

[[ 1  4  9]
 [16 25 36]]
[[11 12 13]
 [14 15 16]]
[[11 12 13]
 [14 15 16]]
